In [1]:
import numpy as np
import pandas as pd

# pandas

In [10]:
cd=pd.read_csv('covid_19_clean_complete_2022.csv')
cd

Province/State        Country/Region        Lat        Long  \
0                 NaN           Afghanistan  33.939110   67.709953   
1                 NaN               Albania  41.153300   20.168300   
2                 NaN               Algeria  28.033900    1.659600   
3                 NaN               Andorra  42.506300    1.521800   
4                 NaN                Angola -11.202700   17.873900   
...               ...                   ...        ...         ...   
214889            NaN    West Bank and Gaza  31.952200   35.233200   
214890            NaN  Winter Olympics 2022  39.904200  116.407400   
214891            NaN                 Yemen  15.552727   48.516388   
214892            NaN                Zambia -13.133897   27.849332   
214893            NaN              Zimbabwe -19.015438   29.154857   

              Date  Confirmed  Deaths  Recovered  Active  \
0       2020-01-22          0       0          0       0   
1       2020-01-22          0       0          0       0   
2       2020-01-22          0       0          0       0   
3       2020-01-22          0       0          0       0   
4       2020-01-22          0       0          0       0   
...            ...        ...     ...        ...     ...   
214889  2022-03-04     649971    5557          0  644414   
214890  2022-03-04        530       0          0     530   
214891  2022-03-04      11774    2135          0    9639   
214892  2022-03-04     313613    3958          0  309655   
214893  2022-03-04     238739    5397          0  233342   

                   WHO Region  
0       Eastern Mediterranean  
1                      Europe  
2                      Africa  
3                      Europe  
4                      Africa  
...                       ...  
214889  Eastern Mediterranean  
214890                    NaN  
214891  Eastern Mediterranean  
214892                 Africa  
214893                 Africa  

[214894 rows x 10 columns]

In [11]:
cd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214894 entries, 0 to 214893
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   Province/State  65705 non-null   object 
 1   Country/Region  214894 non-null  object 
 2   Lat             213348 non-null  float64
 3   Long            213348 non-null  float64
 4   Date            214894 non-null  object 
 5   Confirmed       214894 non-null  int64  
 6   Deaths          214894 non-null  int64  
 7   Recovered       214894 non-null  int64  
 8   Active          214894 non-null  int64  
 9   WHO Region      212575 non-null  object 
dtypes: float64(2), int64(4), object(4)
memory usage: 16.4+ MB


In [14]:
cd.shape

(214894, 10)

In [15]:
cd.describe

<bound method NDFrame.describe of        Province/State        Country/Region        Lat        Long  \
0                 NaN           Afghanistan  33.939110   67.709953   
1                 NaN               Albania  41.153300   20.168300   
2                 NaN               Algeria  28.033900    1.659600   
3                 NaN               Andorra  42.506300    1.521800   
4                 NaN                Angola -11.202700   17.873900   
...               ...                   ...        ...         ...   
214889            NaN    West Bank and Gaza  31.952200   35.233200   
214890            NaN  Winter Olympics 2022  39.904200  116.407400   
214891            NaN                 Yemen  15.552727   48.516388   
214892            NaN                Zambia -13.133897   27.849332   
214893            NaN              Zimbabwe -19.015438   29.154857   

              Date  Confirmed  Deaths  Recovered  Active  \
0       2020-01-22          0       0          0       0   
1    

In [17]:
cd.head(10)

Province/State       Country/Region       Lat        Long  \
0                           NaN          Afghanistan  33.93911   67.709953   
1                           NaN              Albania  41.15330   20.168300   
2                           NaN              Algeria  28.03390    1.659600   
3                           NaN              Andorra  42.50630    1.521800   
4                           NaN               Angola -11.20270   17.873900   
5                           NaN           Antarctica -71.94990   23.347000   
6                           NaN  Antigua and Barbuda  17.06080  -61.796400   
7                           NaN            Argentina -38.41610  -63.616700   
8                           NaN              Armenia  40.06910   45.038200   
9  Australian Capital Territory            Australia -35.47350  149.012400   

         Date  Confirmed  Deaths  Recovered  Active             WHO Region  
0  2020-01-22          0       0          0       0  Eastern Mediterranean  
1  2020-01-22          0       0          0       0                 Europe  
2  2020-01-22          0       0          0       0                 Africa  
3  2020-01-22          0       0          0       0                 Europe  
4  2020-01-22          0       0          0       0                 Africa  
5  2020-01-22          0       0          0       0                    NaN  
6  2020-01-22          0       0          0       0               Americas  
7  2020-01-22          0       0          0       0               Americas  
8  2020-01-22          0       0          0       0                 Europe  
9  2020-01-22          0       0          0       0        Western Pacific

# Numpy

In [19]:
arr=np.array([1,2,3,4,])
arr

array([1, 2, 3, 4])

In [22]:
arr1=np.array(range(10))
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr1=np.arange(2,10,2)
arr1

array([2, 4, 6, 8])

In [24]:
arr1 = np.random.rand(5,5)
arr1

array([[0.02540493, 0.79652347, 0.68188464, 0.68859866, 0.06036764],
       [0.55136892, 0.17228639, 0.63852952, 0.47635603, 0.90068471],
       [0.28765402, 0.64924793, 0.21532248, 0.54221107, 0.06448224],
       [0.41821839, 0.97249595, 0.21048608, 0.80935208, 0.66763802],
       [0.20062477, 0.64408759, 0.24537289, 0.75766884, 0.37909383]])

In [26]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])